module.exports = {
  'unit-no-unknown': null,
  'selector-type-no-unknown': null,
  'font-family-no-missing-generic-family-keyword': null,
  'no-descending-specificity': null,
  'scss/at-import-partial-extension': null,
  'function-url-quotes': null,
  'selector-class-pattern': null,
  'color-function-notation': 'legacy',
  'selector-pseudo-element-no-unknown': null,
  'alpha-value-notation': null,
  'scss/dollar-variable-pattern': null,
  'no-invalid-position-at-import-rule': null,
  'selector-pseudo-class-no-unknown': null,
  'scss/no-global-function-names': null,
  'scss/operator-no-unspaced': null,
  'property-no-unknown': null,
  'selector-pseudo-element-colon-notation': null,
  'at-rule-no-unknown': null,
  'property-case': null,
  'max-line-length': null,
};
